# Generated by Django 3.2.7 on 2022-02-06 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(verbose_name='create date')),
                ('name', models.CharField(max_length=64, verbose_name='plan name')),
                ('pdf', models.FileField(upload_to='plans', verbose_name='plan pdf')),
                ('method', models.CharField(max_length=2, verbose_name='method name')),
                ('team', models.CharField(max_length=64, verbose_name='team name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='plan user')),
            ],
        ),
    ]
